"""Domain model: the vocabulary shared by every layer."""

from support_agent.domain.models import (
    ALLOWED_TRANSITIONS,
    TERMINAL_STATES,
    AgentState,
    Answer,
    Conversation,
    EscalationReason,
    Feedback,
    Intent,
    IntentResult,
    PolicyDecision,
    Provenance,
    ProvenanceKind,
    RefusalReason,
    Step,
    StepKind,
    ToolCall,
    ToolOutcome,
    ToolResult,
    ToolRisk,
    TrustLevel,
    Turn,
    can_transition,
    new_id,
    utc_now,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "TERMINAL_STATES",
    "AgentState",
    "Answer",
    "Conversation",
    "EscalationReason",
    "Feedback",
    "Intent",
    "IntentResult",
    "PolicyDecision",
    "Provenance",
    "ProvenanceKind",
    "RefusalReason",
    "Step",
    "StepKind",
    "ToolCall",
    "ToolOutcome",
    "ToolResult",
    "ToolRisk",
    "TrustLevel",
    "Turn",
    "can_transition",
    "new_id",
    "utc_now",
]
